var TITLE = "HOTS Bingo";
var BOARDTOP = "Heroes of the Storm BINGO";
var FREE = "Team wiped<br>(dead at once)";
var USEFREE = 1;
var AUTOFREE = 0;

allsayings=[
    90,"Taking camp the other team started",
    90,"Taking camp on opponents' side",
    90,"One hero gets a triple kill",
    80,"At least six death potraits visible at once",
    80,"Winning team still has all forts and keeps",
    70,"A team reaches level 24",
    70,"A team gets 15 or more kills",
    70,"Both teams get 10 or more kills",
    70,"Both teams reach level 22 or more",
    50,"Hero killed by a non-hero",
    50,"Fight over the boss",
    50,"Team gets a kill during talent disadvantage",
    40,"Team levels differ by 3",
    30,"Winning team has zero forts and keeps",
    20,"Winning team's core under 25% health",
    50,"Game on Battlefield of Eternity",
    50,"Game on Braxis Holdout",
    50,"Game on Cursed Hollow",
    50,"Game on Dragonshire",
    50,"Game on Infernal Shrines",
    50,"Game on Sky Temple",
    50,"Game on Tomb of the Spider Queen",
    50,"Game on Towers of Doom",
    50,"Game on Volskaya Foundry",
    50,"Game on Warhead Junction",
    6,"Abathur banned",
    6,"Alarak banned",
    6,"Alexstrasza banned",
    6,"Ana banned",
    6,"Anub'arak banned",
    6,"Artanis banned",
    6,"Arthas banned",
    6,"Auriel banned",
    6,"Azmodan banned",
    6,"Blaze banned",
    6,"Brightwing banned",
    6,"Cassia banned",
    6,"Chen banned",
    6,"Cho or Gall banned",
    6,"Chromie banned",
    6,"D.Va banned",
    6,"Deckard banned",
    6,"Dehaka banned",
    6,"Diablo banned",
    6,"E.T.C. banned",
    6,"Falstad banned",
    6,"Fenix banned",
    6,"Garrosh banned",
    6,"Gazlowe banned",
    6,"Genji banned",
    6,"Greymane banned",
    6,"Gul'dan banned",
    6,"Hanzo banned",
    6,"Illidan banned",
    6,"Imperius banned",
    6,"Jaina banned",
    6,"Johanna banned",
    6,"Junkrat banned",
    6,"Kael'thas banned",
    6,"Kel'Thuzad banned",
    6,"Kerrigan banned",
    6,"Kharazim banned",
    6,"Leoric banned",
    6,"Li Li banned",
    6,"Li-Ming banned",
    6,"Lt. Morales banned",
    6,"Lunara banned",
    6,"L&uacute;cio banned",
    6,"Maiev banned",
    6,"Mal'Ganis banned",
    6,"Malfurion banned",
    6,"Malthael banned",
    6,"Medivh banned",
    6,"Mephisto banned",
    6,"Muradin banned",
    6,"Murky banned",
    6,"Nazeebo banned",
    6,"Nova banned",
    6,"Orphea banned",
    6,"Probius banned",
    6,"Ragnaros banned",
    6,"Raynor banned",
    6,"Rehgar banned",
    6,"Rexxar banned",
    6,"Samuro banned",
    6,"Sgt. Hammer banned",
    6,"Sonya banned",
    6,"Stitches banned",
    6,"Stukov banned",
    6,"Sylvanas banned",
    6,"Tassadar banned",
    6,"The Butcher banned",
    6,"The Lost Vikings banned",
    6,"Thrall banned",
    6,"Tracer banned",
    6,"Tychus banned",
    6,"Tyrael banned",
    6,"Tyrande banned",
    6,"Uther banned",
    6,"Valeera banned",
    6,"Valla banned",
    6,"Varian banned",
    6,"Whitemane banned",
    6,"Xul banned",
    6,"Yrel banned",
    6,"Zagara banned",
    6,"Zarya banned",
    6,"Zeratul banned",
    6,"Zul'jin banned",
    10,"Abathur picked",
    10,"Alarak picked",
    10,"Alexstrasza picked",
    10,"Ana picked",
    10,"Anub'arak picked",
    10,"Artanis picked",
    10,"Arthas picked",
    10,"Auriel picked",
    10,"Azmodan picked",
    10,"Blaze picked",
    10,"Brightwing picked",
    10,"Cassia picked",
    10,"Chen picked",
    10,"Cho'gall picked",
    10,"Chromie picked",
    10,"D.Va picked",
    10,"Deckard picked",
    10,"Dehaka picked",
    10,"Diablo picked",
    10,"E.T.C. picked",
    10,"Falstad picked",
    10,"Fenix picked",
    10,"Garrosh picked",
    10,"Gazlowe picked",
    10,"Genji picked",
    10,"Greymane picked",
    10,"Gul'dan picked",
    10,"Hanzo picked",
    10,"Illidan picked",
    10,"Imperius picked",
    10,"Jaina picked",
    10,"Johanna picked",
    10,"Junkrat picked",
    10,"Kael'thas picked",
    10,"Kel'Thuzad picked",
    10,"Kerrigan picked",
    10,"Kharazim picked",
    10,"Leoric picked",
    10,"Li Li picked",
    10,"Li-Ming picked",
    10,"Lt. Morales picked",
    10,"Lunara picked",
    10,"L&uacute;cio picked",
    10,"Maiev picked",
    10,"Mal'Ganis picked",
    10,"Malfurion picked",
    10,"Malthael picked",
    10,"Medivh picked",
    10,"Mephisto picked",
    10,"Muradin picked",
    10,"Murky picked",
    10,"Nazeebo picked",
    10,"Nova picked",
    10,"Orphea picked",
    10,"Probius picked",
    10,"Ragnaros picked",
    10,"Raynor picked",
    10,"Rehgar picked",
    10,"Rexxar picked",
    10,"Samuro picked",
    10,"Sgt. Hammer picked",
    10,"Sonya picked",
    10,"Stitches picked",
    10,"Stukov picked",
    10,"Sylvanas picked",
    10,"Tassadar picked",
    10,"The Butcher picked",
    10,"The Lost Vikings picked",
    10,"Thrall picked",
    10,"Tracer picked",
    10,"Tychus picked",
    10,"Tyrael picked",
    10,"Tyrande picked",
    10,"Uther picked",
    10,"Valeera picked",
    10,"Valla picked",
    10,"Varian picked",
    10,"Whitemane picked",
    10,"Xul picked",
    10,"Yrel picked",
    10,"Zagara picked",
    10,"Zarya picked",
    10,"Zeratul picked",
    10,"Zul'jin picked",
];
