var sayings = [
    "A king",
    "A parable",
    "A question",
    "A statistic",
    "A tree",
    "Adam, Eve, or Eden",
    "Agency",
    "Almost laughing at own joke",
    "An Article of Faith",
    "An animal",
    "Angels",
    "Any word starting with 'K'",
    "Any word starting with 'Q'",
    "Any word starting with 'V'",
    "Asian nation or region",
    "Atonement",
    "Aviation",
    "Baptism",
    "Bishops",
    "Blessings",
    "Blindness",
    "Brigham Young",
    "Canada",
    "Celestial Kingdom",
    "Charity",
    "Chastity",
    "Choir member's head shaking",
    "Christianity",
    "Commandments",
    "Confirmation",
    "Covenants or promises",
    "Creation",
    "Daughters",
    "Death",
    "Dictionary definition",
    "Doubt or unbelief",
    "Dramatic hand gesture",
    "Dreams",
    "Education",
    "Eternity",
    "European nation or region",
    "Exercise",
    "Faith",
    "Families",
    "Fasting",
    "Fathers",
    "Fear",
    "Female speaker",
    "Food storage",
    "Forgiveness",
    "Friends",
    "Fruit",
    "Gambling",
    "Garden of Eden",
    "Genealogy",
    "General auxiliary president or counselor",
    "Gesturing as visual aid",
    "Gethsemane",
    "Glory",
    "God's omnipotence",
    "God's omniscience",
    "Gold plates",
    "Gospel",
    "Grace",
    "Gratitude",
    "Hate",
    "Hell",
    "Home or visiting teaching",
    "Honesty or integrity",
    "Hope",
    "Humility",
    "Idaho",
    "Integrity",
    "Internet",
    "Investigators",
    "Island nation",
    "Jesus (before testimony)",
    "Joseph Smith",
    "Journals",
    "Joy",
    "Justice or judgement",
    "Keys",
    "Kindness",
    "Knowledge",
    "Laws",
    "Legacy",
    "Light",
    "Love",
    "Magnifying callings",
    "Male speaker with little white or grey hair",
    "Marriage",
    "Men",
    "Mercy",
    "Messiah",
    "Mexico",
    "Miracles",
    "Mission story",
    "Missionary work",
    "Modesty",
    "Money",
    "Moses",
    "Mothers",
    "Movies, TV, or music",
    "Nephi",
    "Numbered list",
    "Obedience",
    "Offense",
    "Ordinances",
    "Patience",
    "Paul",
    "Peace",
    "Personal finances",
    "Pioneers",
    "Plan of salvation",
    "Prayer",
    "Premortal life",
    "Pride",
    "Priesthood",
    "Primary",
    "Prime-numbered hymn",
    "Prophets",
    "Quoting a living apostle",
    "Quoting same scripture as another talk this conference",
    "Redeemer",
    "Relief Society",
    "Repentance",
    "Restoration",
    "Resurrection",
    "Revelation",
    "Reverence",
    "Sabbath observance",
    "Sacrament",
    "Sacrifice",
    "Salt Lake City",
    "Satan",
    "Scripture study",
    "Second coming",
    "Service",
    "Setting an example",
    "Sharing a Book of Mormon scripture",
    "Sharing a D&C scripture",
    "Sharing a New Testament scripture",
    "Sharing an Old Testament scripture",
    "Signs",
    "Simplicity",
    "Sin",
    "Someone in congrgation noticing camera",
    "Sons",
    "South American nation or region",
    "Speaker coughs or gets choked up",
    "Speaker wears blue tie",
    "Speaker wears red tie",
    "Speaker's personal experience",
    "Spirits",
    "Sports",
    "Story about children",
    "Story about sickness",
    "Strength",
    "Talents",
    "Temples",
    "Temporal bodies",
    "Testimonies",
    "The Book of Mormon",
    "The Holy Ghost",
    "The United States",
    "Time",
    "Tithing",
    "Trials",
    "Truth",
    "Two people at organ",
    "Unity",
    "Utah",
    "Video, photo, or quote appearing on screen",
    "Virtue",
    "Widows",
    "Wisdom",
    "Witness",
    "Women",
    "Word of Wisdom",
    "Work",
    "Worship",
    "Worthiness",
    "Zion",
    "\"Beloved prophet\"",
    "\"Close quote\"",
    "\"Daily lives\"",
    "\"Endure to the end\"",
    "\"Ensign\" magazine",
    "\"Eternal family\" or \"companion\"",
    "\"Every member a missionary\"",
    "\"Fellowship\" as a verb",
    "\"Fiber of my being\"",
    "\"I'd like to address my comments to\"",
    "\"I'd like to bear my testimony\"",
    "\"It's a pleasure to speak to you\"",
    "\"Many years ago\"",
    "\"Social media\" or a specific service",
    "\"Supernal\"",
    "\"Ward family\"",
    "\"What would Jesus do\"",
];

