var allsayings = [
    1,"Almost laughing at own joke",
    1,"Aviation",
    1,"Brigham Young",
    1,"Canada",
    1,"Choir member's head shaking",
    1,"Christianity",
    1,"Dictionary definition",
    1,"Dramatic hand gesture",
    1,"Dreams",
    1,"Espressing feelings about assignment to speak",
    1,"Fruit",
    1,"Idaho",
    1,"Island nation",
    1,"Magnifying callings",
    1,"Male speaker with little white or grey hair",
    1,"Mexico",
    1,"Numbered list",
    1,"Paul",
    1,"Prime-numbered hymn",
    1,"Quoting same scripture as another talk this conference",
    1,"Redeemer",
    1,"Someone in congrgation noticing camera",
    1,"South American nation or region",
    1,"Speaker coughs or gets choked up",
    1,"The United States",
    1,"Widows",
    1,"\"Beloved prophet\"",
    1,"\"Daily lives\"",
    1,"\"Every member a missionary\"",
    1,"\"Fiber of my being\"",
    1,"\"Many years ago\"",
    1,"\"Quote\"",
    1,"\"Social media\" or a specific service",
    1,"\"What would Jesus do\"",
    10,"Agency",
    10,"Atonement",
    10,"Baptism",
    10,"Blessings",
    10,"Charity",
    10,"Commandments",
    10,"Covenants or promises",
    10,"Death",
    10,"Doubt or unbelief",
    10,"Faith",
    10,"Families",
    10,"Forgiveness",
    10,"Gospel",
    10,"Gratitude",
    10,"Honesty or integrity",
    10,"Hope",
    10,"Humility",
    10,"Integrity",
    10,"Jesus (before testimony)",
    10,"Joy",
    10,"Justice or judgement",
    10,"Kindness",
    10,"Knowledge",
    10,"Love",
    10,"Marriage",
    10,"Mercy",
    10,"Missionary work",
    10,"Obedience",
    10,"Ordinances",
    10,"Patience",
    10,"Peace",
    10,"Prayer",
    10,"Pride",
    10,"Priesthood",
    10,"Prophets",
    10,"Repentance",
    10,"Resurrection",
    10,"Revelation",
    10,"Reverence",
    10,"Sabbath observance",
    10,"Sacrament",
    10,"Sacrifice",
    10,"Scripture study",
    10,"Service",
    10,"Sharing a Book of Mormon scripture",
    10,"Sharing a D&C scripture",
    10,"Sharing a New Testament scripture",
    10,"Speaker's personal experience",
    10,"The Book of Mormon",
    10,"The Holy Ghost",
    10,"Tithing",
    10,"Word of Wisdom",
    2,"Gambling",
    2,"Gethsemane",
    2,"Gold plates",
    2,"Keys",
    2,"Messiah",
    2,"Moses",
    2,"Movies, TV, or music",
    2,"Quoting a living apostle",
    2,"Simplicity",
    2,"Sports",
    2,"Two people at organ",
    2,"Utah",
    2,"\"Ensign\" magazine",
    3,"A parable",
    3,"A question",
    3,"A statistic",
    3,"Food storage",
    3,"Glory",
    3,"Hell",
    3,"Internet",
    3,"Investigators",
    3,"Journals",
    3,"Video, photo, or quote appearing on screen",
    3,"\"Supernal\"",
    4,"An Article of Faith",
    4,"Fellowship",
    4,"Friends",
    4,"God's omnipotence",
    4,"God's omniscience",
    4,"Grace",
    4,"Hate",
    4,"Light",
    4,"Mission story",
    4,"Modesty",
    4,"Money",
    4,"Nephi",
    4,"Offense",
    4,"Pioneers",
    4,"Primary",
    4,"Salt Lake City",
    4,"Spirits",
    4,"Strength",
    4,"Talents",
    4,"Time",
    4,"Witness",
    4,"Worthiness",
    4,"Zion",
    5,"A king",
    5,"A tree",
    5,"Asian nation or region",
    5,"Chastity",
    5,"Confirmation",
    5,"Daughters",
    5,"Education",
    5,"Eternity",
    5,"European nation or region",
    5,"Exercise",
    5,"Fathers",
    5,"Legacy",
    5,"Men",
    5,"Mothers",
    5,"Premortal life",
    5,"Relief Society",
    5,"Signs",
    5,"Sons",
    5,"Specifying a target audience",
    5,"Women",
    5,"\"Eternal family\" or \"companion\"",
    6,"Adam, Eve, or Eden",
    6,"An animal",
    6,"Creation",
    6,"Fasting",
    6,"Joseph Smith",
    6,"Miracles",
    6,"Satan",
    6,"Setting an example",
    6,"Speaker wears blue tie",
    6,"Speaker wears red tie",
    7,"Any word starting with 'K'",
    7,"Any word starting with 'Q'",
    7,"Any word starting with 'V'",
    7,"Bodies",
    7,"Celestial Kingdom",
    7,"Fear",
    7,"Female speaker",
    7,"Laws",
    7,"Plan of salvation",
    7,"Second coming",
    7,"Virtue",
    7,"Wisdom",
    7,"\"Endure to the end\"",
    8,"Bishops",
    8,"Blindness",
    8,"Ministering",
    8,"Restoration",
    8,"Sharing an Old Testament scripture",
    8,"Story about sickness",
    8,"Truth",
    8,"Unity",
    8,"Worship",
    9,"Angels",
    9,"Sin",
    9,"Story about children",
    9,"Temples",
    9,"Testimonies",
    9,"Trials",
    9,"Work",
];

