var allsayings = [
    1,"Detective accidentally says too much",
    1,"Handedness",
    1,"Initials",
    1,"People pretending to be strangers",
    10,"An argument",
    10,"Blackmail",
    10,"Confronted for lying",
    2,"A Newspaper",
    2,"Conspiracy to murder",
    2,"False confession",
    2,"Mistaken identity",
    2,"Solving an old case too",
    2,"Unsafe driving",
    3,"A lawyer",
    3,"A note or letter",
    3,"A party",
    3,"Changed or faked name",
    3,"Death threat",
    3,"Detective lies or lays a trap",
    3,"Police error",
    4,"Interviewee says too much",
    4,"Multiple deaths",
    4,"Overheard conversation",
    4,"Police station",
    4,"Rush to catch suspect",
    4,"Theft",
    5,"A family secret",
    5,"A photograph",
    5,"Body was moved",
    5,"Formal arrest",
    5,"Planted evidence",
    5,"Wanting or already having a divorce",
    6,"Actual, apparent, or attempted suicide",
    6,"An affair",
    6,"Unconfirmable alibi",
    6,"Unlikeable victim",
    7,"A doctor",
    7,"Admitting happiness at death",
    7,"An autopsy",
    7,"Solution reveal during confrontation",
    7,"Visible epiphany",
    8,"Sneaking around at night",
    8,"Time of death",
    9,"A scream",
    9,"Will or inheritance",
];


