var allsayings = [
    10,"An argument",
    10,"Blackmail",
    10,"Caught in a lie",
    10,"Time of death",
    2,"Conspiracy to murder",
    7,"Admitting happiness at death",
    4,"Police station",
    2,"A party",
    2,"False confession",
    2,"Mistaken identity",
    2,"Theft",
    3,"A lawyer",
    3,"Bumbling police",
    3,"Vengence killing",
    4,"A family secret",
    4,"After solving case, rush to catch culprit",
    4,"Body was moved",
    4,"Interviewee says too much",
    4,"Multiple deaths",
    5,"A doctor",
    5,"Formal arrest",
    1,"People pretending to be strangers",
    5,"Planted evidence",
    5,"Solving an old crime too",
    5,"Unlikeable victim",
    6,"Actual or apparent suicide",
    6,"An affair",
    2,"A Newspaper",
    4,"Overheard conversation",
    6,"Suspect claims to be alone at time of murder",
    7,"An autopsy",
    7,"Solution reveal during confrontation",
    7,"Visible epiphany",
    8,"Sneaking around at night",
    9,"Will or inheritance",
    1,"Detective accidentally says too much",
    3,"Detective lays a trap",
    3,"Detective lies",
    9,"A scream",
    4,"Changed or faked name",
    1,"Initials",
    3,"Threatening to kill someone",
    1,"Handedness",
    9,"A photograph",
    5,"Wanting or already having a divorce",
];


