var sayings = [
    "A restaurant",
    "A warning",
    "Beams",
    "Complaining about professors",
    "His kids in the lab",
    "\"I don't want to force you\"",
    "\"That or I won't let you graduate\"",
    "Cars",
    "Civil engineers",
    "Data",
    "Degrees of freedom",
    "Disc drive",
    "Drinking coffee",
    "Email about current events (like a news article)",
    "Email with incomplete sentences",
    "Email with spelling error",
    "Equal and opposite",
    "Ethics",
    "Flight of the Conchords",
    "Free body diagram",
    "Frequency",
    "Grant money",
    "Has foreign visitor",
    "He forgets equipment for a presentation",
    "Helicopters",
    "Laughing",
    "Life advice",
    "Lunch",
    "Mac computers",
    "Massive mass",
    "Mathematicians",
    "Meetings",
    "Mentioning cell phones/cases",
    "Message on Slack",
    "Mother-in-law",
    "Movie/video quote or immitation",
    "Offering coffee",
    "Office hours",
    "Perfection",
    "Politics",
    "Resonance",
    "Runs out of time",
    "Sends an email after midnight",
    "Shake",
    "Sinusoidal",
    "Springs",
    "Steady state equations",
    "Story about industry",
    "String",
    "Suddenly shouting",
    "Talking about coffee",
    "The lab",
    "Undergrads",
    "University policy",
    "Using a nickname",
    "Zero",
    "\"Build a wall\"",
    "\"C'mon guys\"",
    "\"Get everything in writing\"",
    "\"How does this work?\"",
    "\"I'll get around to reading your paper\"",
    "\"In real life\"",
    "\"No volunteers?\"",
    "\"Pitfalls\"",
    "\"Right?\"",
    "\"That's expensive\"",
    "\"Very good\"",
    "\"What is this term?\"",
    "\"Where is everybody?\"",
    "\"With your eyes closed\"",
];


