var TITLE = "Sacrament Meeting Bingo";
var BOARDTOP = "LDS Sacrament Meeting Bingo";
var FREE = "FREE";
var USEFREE = 1;
var AUTOFREE = 1;
var allsayings = [
    10,"\"Good [time] brothers and sisters\"",
    10,"\"For those who don't know me\"",
    10,"\"Endure to the end\"",
    10,"Story about sickness",
    10,"Story about children",
    10,"Sharing a New Testament scripture",
    10,"Sharing a Book of Mormon scripture",
    10,"Self-aggrandizement",
    10,"Prayer",
    10,"Missionary work",
    10,"Church",
    10,"At least 3 minutes introducing self",
    9,"\"By the same sign\"",
    9,"Truth",
    8,"\"As I prepared\"",
    8,"Trials",
    8,"Temple",
    8,"Sabbath observance",
    8,"Marriage",
    7,"\"Special musical number\"",
    7,"\"If you're here please stand\"",
    7,"Sports",
    7,"Reading from materials for more than 10 seconds",
    7,"Family history work",
    7,"Faith",
    6,"\"Umm\"",
    6,"\"Daily lives\"",
    6,"Testimonies",
    6,"Social media",
    5,"\"Thank you, that was wonderful/beautiful\"",
    5,"Word of Wisdom",
    5,"Women",
    5,"Stake business",
    5,"Service",
    5,"Repentance",
    5,"Prophets",
    5,"Priesthood",
    5,"Pride",
    5,"Men",
    5,"Joseph Smith",
    5,"Jesus (before testimony)",
    5,"Celestial Kingdom",
    5,"Blessing",
    4,"\"When I was asked to speak\"",
    4,"\"Thy son\" while closing a talk",
    4,"\"The family is under attack\"",
    4,"\"Nonmember\"",
    4,"\"Eternal family\"",
    4,"The Holy Ghost",
    4,"Teaching",
    4,"Spirit",
    4,"Sharing a Old Testament scripture",
    4,"Sharing a D&C scripture",
    4,"Referencing secular media",
    4,"Parable",
    4,"Investigator",
    4,"Hope",
    4,"Gratitude",
    3,"\"What would Jesus do\"",
    3,"\"This talk is for me\"",
    3,"\"The church/gospel/truth is (2 or more of) [restored] [back] [on the Earth] [again] [for our time]\"",
    3,"\"Ten commandments\"",
    3,"\"Opposed if any\"",
    3,"\"It's a pleasure to speak to/be with you today\"",
    3,"\"I've been asked to speak on\"",
    3,"Worthiness",
    3,"Work",
    3,"Utah",
    3,"Thomas S. Monson",
    3,"Talents",
    3,"Sacrifice",
    3,"Sacrament",
    3,"Resurrection",
    3,"Peace",
    3,"Patience",
    3,"Offense",
    3,"Love",
    3,"Crinkling wrapper",
    3,"Bishop",
    3,"Baptism",
    3,"Any word that starts with 'V'",
    3,"Any word that starts with 'Q'",
    3,"Any word that starts with 'K'",
    2,"\"When I was on my mission\"",
    2,"\"Ward family\"",
    2,"\"There were [number] members at my school\"",
    2,"\"Tender mercy\"",
    2,"\"Sweet spirit\"",
    2,"\"For me personally\"",
    2,"Wisdom",
    2,"Unbelief",
    2,"Tithing",
    2,"Signs",
    2,"Satan",
    2,"Obedience",
    2,"Nephi",
    2,"Money",
    2,"Laugh at own joke",
    2,"Esoteric analogy",
    2,"Charity",
    2,"An animal",
    1,"\"We'll go to that point\"",
    1,"\"Sunday school/primary answers\"",
    1,"\"Sorry for crying\"",
    1,"\"Shadow of a doubt\"",
    1,"\"Pre-existence\"",
    1,"\"My favorite scripture/hymn\"",
    1,"\"Mormon standard time\"",
    1,"\"If you could turn with me\"",
    1,"\"I'm grateful for the opportunity\"",
    1,"\"I'd like to bear my testimony\"",
    1,"\"Focus on The One\"",
    1,"\"Fiber of my being\"",
    1,"\"Fellowship\" as a verb",
    1,"\"Every member a missionary\"",
    1,"\"Eternal companion\"",
    1,"\"Ensign\" magazine",
    1,"\"Comfort zone/bubble\"",
    1,"\"Bear with me\"",
    1,"\"Alooo-HA!\"",
    1,"Zion",
    1,"Virtue",
    1,"Time",
    1,"Temporal bodies",
    1,"Talk outline",
    1,"Strength",
    1,"Speaking in a foreign language",
    1,"Speaker adjusts microphone",
    1,"Someone sneezes",
    1,"Someone sleeping",
    1,"Someone on the stand wearing a red tie",
    1,"Someone blows their nose",
    1,"Simpleness",
    1,"Reverence",
    1,"Revelation",
    1,"Prime-numbered hymn",
    1,"Pride cycle",
    1,"Podium height adjusted",
    1,"Pioneers",
    1,"Modesty",
    1,"Miracle",
    1,"Mercy",
    1,"Magnifying callings",
    1,"Knowledge",
    1,"Kindness",
    1,"Justice",
    1,"Joy",
    1,"Journal",
    1,"Integrity",
    1,"Idaho",
    1,"Humility",
    1,"Hell",
    1,"Hate",
    1,"God's omniscience",
    1,"God's omnipotence",
    1,"Glory",
    1,"Gethsemane",
    1,"Garden of Eden",
    1,"Food storage",
    1,"Fear",
    1,"Fasting",
    1,"Example",
    1,"Eternity",
    1,"Education",
    1,"Dream",
    1,"Dictionary definition",
    1,"Death",
    1,"Creation",
    1,"Covenant",
    1,"Congregation stands for a hymn",
    1,"Confirmation",
    1,"Chastity",
    1,"Cell phone rings",
    1,"Brigham Young",
    1,"Blindness",
    1,"Baldness",
    1,"Atonement",
    1,"Articles of faith",
    1,"Angel",
    1,"Agency",
    1,"Adam and Eve",
    1,"A reference to the length of the meeting",
    1,"A reference to how often the speaker bears public testimony",
    1,"A personal experience",
    1,"A living apostle",
    1,"A confession",
    1,"A URL",
];
