var TITLE = "General Conference Bingo";
var BOARDTOP = "General Conference BINGO";
var FREE = "Jesus Christ";
var USEFREE = 1;
var AUTOFREE = 0;

var allsayings = [
    10,"\"The Church of Jesus Christ of Latter-day Saints\"",
    10,"Word of Wisdom",
    10,"Tithing",
    10,"The Holy Ghost",
    10,"The Book of Mormon (including quotation)",
    10,"Speaker's personal experience",
    10,"New Testament quotation",
    10,"Service",
    10,"Scripture study",
    10,"Sacrament",
    10,"Sabbath observance",
    10,"Reverence",
    10,"Revelation",
    10,"Resurrection",
    10,"Repentance",
    10,"Prophets",
    10,"Priesthood",
    10,"Pride",
    10,"Prayer",
    10,"Peace",
    10,"Patience",
    10,"Ordinances",
    10,"Obedience",
    10,"Missionary work",
    10,"Marriage",
    10,"Love",
    10,"Life of Jesus",
    10,"Kindness",
    10,"Justice or judgement",
    10,"Happiness",
    10,"Joseph Smith",
    10,"Humility",
    10,"Hope",
    10,"Integrity",
    10,"Gratitude",
    10,"Gospel",
    10,"Forgiveness",
    10,"Families",
    10,"Faith",
    10,"Doubt or unbelief",
    10,"Death",
    10,"Covenants or promises",
    10,"Commandments",
    10,"Charity",
    10,"Blessings",
    10,"Baptism",
    10,"Atonement",
    9,"D&C quotation",
    9,"Work",
    9,"Testimonies",
    9,"Temples",
    9,"Sin",
    9,"Sacrifice",
    8,"Worship",
    8,"Unity",
    8,"Truth",
    8,"Temptation",
    8,"Sickness or injury",
    8,"Old Testament quotation",
    8,"Restoration",
    8,"Ministering",
    8,"Mercy",
    8,"Knowledge",
    8,"Evil",
    8,"Bishops",
    8,"Agency",
    7,"\"Endure to the end\"",
    7,"Wisdom",
    7,"Virtue",
    7,"Second coming",
    7,"Plan of salvation",
    7,"Music or hymns",
    7,"Laws",
    7,"Food",
    7,"Female speaker",
    7,"Fear",
    7,"Children",
    7,"Celestial Kingdom",
    7,"Bodies",
    7,"Any word starting with 'V'",
    7,"Any word starting with 'U'",
    7,"Any word starting with 'Q'",
    7,"Any word starting with 'K'",
    7,"Angels",
    6,"Time",
    6,"Speaker wears red tie",
    6,"Speaker wears blue tie",
    6,"Setting an example",
    6,"Satan",
    6,"Miracles",
    6,"Light",
    6,"Fasting",
    6,"Creation",
    6,"An animal",
    6,"Adam, Eve, or Eden",
    5,"\"Beloved\"",
    5,"Women",
    5,"Trials or burdens",
    5,"Sorrow or depression",
    5,"Sons",
    5,"Signs",
    5,"Relief Society",
    5,"Premortal life",
    5,"Mothers",
    5,"Men",
    5,"Legacy",
    5,"Fathers",
    5,"Exercise",
    5,"European nation or region",
    5,"Eternity",
    5,"Education",
    5,"Daughters",
    5,"Confirmation",
    5,"Chastity",
    5,"Asian nation or region",
    5,"A tree",
    5,"A king",
    4,"Zion",
    4,"Worthiness",
    4,"Witness",
    4,"The Veil",
    4,"Talents",
    4,"Strength",
    4,"Spirits",
    4,"Shepherd or sheep",
    4,"Salt Lake City",
    4,"Primary",
    4,"Pioneers",
    4,"Pain",
    4,"Offense",
    4,"Nephi",
    4,"Money",
    4,"Modesty",
    4,"Mission story",
    4,"Hate",
    4,"Grace",
    4,"God's omniscience",
    4,"God's omnipotence",
    4,"Friends",
    4,"Fellowship",
    4,"Eternal",
    4,"Dispensation",
    4,"An Article of Faith",
    3,"\"Supernal\"",
    3,"\"Historic\"",
    3,"Video, photo, or quote appearing on screen",
    3,"Sharing",
    3,"Power",
    3,"Journals",
    3,"Investigators",
    3,"Glory",
    3,"Family history or genealogy",
    3,"Entertainment, movies, TV, or video games",
    3,"Courage",
    3,"A statistic",
    3,"A question",
    3,"A parable",
    3,"A definition",
    2,"\"Ensign\" or \"Liahona\" magazine",
    2,"Utah",
    2,"Two people at organ",
    2,"Sports",
    2,"Specifying a target audience",
    2,"Song not in LDS hymnal",
    2,"Quoting a living apostle",
    2,"Procrastination",
    2,"Prime-numbered hymn",
    2,"Perfection",
    2,"Moses",
    2,"Messiah",
    2,"Keys",
    2,"Healing",
    2,"Gold plates",
    2,"Gethsemane",
    2,"Gambling",
    2,"Confession",
    2,"An airplane",
    2,"A hand gesture",
    1,"\"Social media\" or a specific service",
    1,"\"Daily lives\"",
    1,"Widows",
    1,"Debt",
    1,"The United States",
    1,"South American nation or region",
    1,"Simplicity",
    1,"Redeemer",
    1,"Quoting same material as another talk this conference",
    1,"Paul",
    1,"Numbered list",
    1,"Mexico",
    1,"Member missionary work",
    1,"Magnifying callings",
    1,"Island nation",
    1,"Idaho",
    1,"Hell",
    1,"Fruit",
    1,"Dreams",
    1,"Congregation noticing camera",
    1,"Comments on speaking assignment",
    1,"Christianity",
    1,"Canada",
    1,"Brigham Young",
    1,"Blindness",
    1,"A joke",
    1,"A cough",
];

