var TITLE = "General Conference Bingo";
var BOARDTOP = "General Conference BINGO";
var FREE = "Jesus Christ";
var USEFREE = 1;
var AUTOFREE = 0;

var allsayings = [
    32,"Atonement",
    32,"Baptism",
    32,"Blessings",
    32,"Charity",
    32,"Commandments",
    32,"Covenants or promises",
    32,"D&C quotation",
    32,"Death",
    32,"Doubt or unbelief",
    32,"Faith",
    32,"Families",
    32,"Forgiveness",
    32,"Gospel",
    32,"Gratitude",
    32,"Happiness",
    32,"Hope",
    32,"Humility",
    32,"Integrity",
    32,"Joseph Smith",
    32,"Justice or judgement",
    32,"Kindness",
    32,"Life of Jesus",
    32,"Love",
    32,"Marriage",
    32,"Missionary work",
    32,"New Testament quotation",
    32,"Obedience",
    32,"Ordinances",
    32,"Patience",
    32,"Peace",
    32,"Prayer",
    32,"Pride",
    32,"Priesthood",
    32,"Prophets",
    32,"Repentance",
    32,"Resurrection",
    32,"Revelation",
    32,"Reverence",
    32,"Sabbath observance",
    32,"Sacrament",
    32,"Scripture study",
    32,"Service",
    32,"Sin",
    32,"Speaker's personal experience",
    32,"Temples",
    32,"Testimonies",
    32,"The Book of Mormon (generally or quotation)",
    32,"The Holy Ghost",
    32,"Tithing",
    32,"Word of Wisdom",
    32,"Work",
    32,"\"The Church of Jesus Christ of Latter-day Saints\"",
    32,"Sacrifice",
    16,"Agency",
    16,"Angels",
    16,"Any word starting with 'K'",
    16,"Any word starting with 'Q'",
    16,"Any word starting with 'U'",
    16,"Any word starting with 'V'",
    16,"Bishops",
    16,"Bodies",
    16,"Celestial Kingdom",
    16,"Children",
    16,"Evil",
    16,"Fear",
    16,"Female speaker",
    16,"Food",
    16,"Knowledge",
    16,"Laws",
    16,"Mercy",
    16,"Ministering",
    16,"Music or hymns",
    16,"Old Testament quotation",
    16,"Plan of salvation",
    16,"Restoration",
    16,"Second coming",
    16,"Sickness or injury",
    16,"Temptation",
    16,"Truth",
    16,"Unity",
    16,"Virtue",
    16,"Wisdom",
    16,"Worship",
    16,"\"Endure to the end\"",
    8,"A tree",
    8,"Adam, Eve, or Eden",
    8,"An animal",
    8,"Asian nation or region",
    8,"Chastity",
    8,"Confirmation",
    8,"Creation",
    8,"Daughters",
    8,"Education",
    8,"Eternity",
    8,"European nation or region",
    8,"Exercise",
    8,"Fasting",
    8,"Fathers",
    8,"Legacy",
    8,"Light",
    8,"Men",
    8,"Miracles",
    8,"Mothers",
    8,"Premortal life",
    8,"Relief Society",
    8,"Satan",
    8,"Setting an example",
    8,"Signs",
    8,"Sons",
    8,"Sorrow or depression",
    8,"Speaker wears blue tie",
    8,"Speaker wears red tie",
    8,"Time",
    8,"Trials or burdens",
    8,"Women",
    8,"\"Beloved\"",
    8,"A king",
    4,"Zion",
    4,"A definition",
    4,"A parable",
    4,"A question",
    4,"A statistic",
    4,"An Article of Faith",
    4,"Courage",
    4,"Dispensation",
    4,"Entertainment, movies, TV, or video games",
    4,"Eternal",
    4,"Family history or genealogy",
    4,"Fellowship",
    4,"Friends",
    4,"Glory",
    4,"God's omnipotence",
    4,"God's omniscience",
    4,"Grace",
    4,"Hate",
    4,"Investigators",
    4,"Journals",
    4,"Mission story",
    4,"Modesty",
    4,"Money",
    4,"Nephi",
    4,"Offense",
    4,"Pain",
    4,"Pioneers",
    4,"Power",
    4,"Primary",
    4,"Salt Lake City",
    4,"Sharing",
    4,"Shepherd or sheep",
    4,"Spirits",
    4,"Strength",
    4,"Talents",
    4,"The Veil",
    4,"Video, photo, or quote appearing on screen",
    4,"Witness",
    4,"Worthiness",
    4,"\"Historic\"",
    4,"\"Supernal\"",
    2,"A hand gesture",
    2,"An airplane",
    2,"Confession",
    2,"Gambling",
    2,"Gethsemane",
    2,"Gold plates",
    2,"Healing",
    2,"Keys",
    2,"Messiah",
    2,"Moses",
    2,"Perfection",
    2,"Choir sings prime-numbered hymn",
    2,"Procrastination",
    2,"Quoting a living apostle",
    2,"Song not in LDS hymnal",
    2,"Specifying a target audience",
    2,"Sports",
    2,"Two people at organ",
    2,"Utah",
    2,"\"Ensign\" or \"Liahona\" magazine",
    1,"A cough",
    1,"A joke",
    1,"Blindness",
    1,"Brigham Young",
    1,"Canada",
    1,"Christianity",
    1,"Comments on speaking assignment",
    1,"Congregation noticing camera",
    1,"Debt",
    1,"Dreams",
    1,"Fruit",
    1,"Hell",
    1,"Idaho",
    1,"Island nation",
    1,"Magnifying callings",
    1,"Member missionary work",
    1,"Mexico",
    1,"Numbered list",
    1,"Paul",
    1,"Quoting same material as another talk this conference",
    1,"Redeemer",
    1,"Simplicity",
    1,"South American nation or region",
    1,"The United States",
    1,"Widows",
    1,"\"Daily lives\"",
    1,"\"Social media\" or a specific service",
];

