var TITLE = "General Conference Bingo";
var BOARDTOP = "General Conference BINGO";
var FREE = "FREE";
var USEFREE = 1;
var AUTOFREE = 1;

var allsayings = [
    1,"A cough",
    1,"A joke",
    1,"Blindness",
    1,"Brigham Young",
    1,"Canada",
    1,"Christianity",
    1,"Congregation noticing camera",
    1,"Dreams",
    1,"Expressing feelings about assignment to speak",
    1,"Fruit",
    1,"Hell",
    1,"Idaho",
    1,"Island nation",
    1,"Magnifying callings",
    1,"Member missionary work",
    1,"Mexico",
    1,"Numbered list",
    1,"Paul",
    2,"Prime-numbered hymn",
    2,"Song not in LDS hymnal",
    1,"Quoting same material as another talk this conference",
    1,"Redeemer",
    1,"Simplicity",
    1,"South American nation or region",
    1,"The United States",
    1,"Widows",
    1,"\"Daily lives\"",
    1,"\"Social media\" or a specific service",
    10,"Atonement",
    10,"Baptism",
    10,"Blessings",
    10,"Charity",
    10,"Commandments",
    10,"Covenants or promises",
    10,"Death",
    10,"Doubt or unbelief",
    10,"Faith",
    10,"Families",
    10,"Forgiveness",
    10,"Gospel",
    10,"Gratitude",
    10,"Honesty or integrity",
    10,"Hope",
    10,"Humility",
    10,"Joy or happiness",
    10,"Justice or judgement",
    10,"Kindness",
    10,"Love",
    10,"Marriage",
    10,"Missionary work",
    10,"Obedience",
    10,"Ordinances",
    10,"Patience",
    10,"Peace",
    10,"Prayer",
    10,"Pride",
    10,"Priesthood",
    10,"Prophets",
    10,"Repentance",
    10,"Resurrection",
    10,"Revelation",
    10,"Reverence",
    10,"Sabbath observance",
    10,"Sacrament",
    10,"Scripture study",
    10,"Service",
    10,"Sharing a Book of Mormon scripture",
    10,"Sharing a D&C scripture",
    10,"Sharing a New Testament scripture",
    10,"Speaker's personal experience",
    10,"The Book of Mormon",
    10,"The Holy Ghost",
    10,"Tithing",
    10,"Word of Wisdom",
    2,"A hand gesture",
    2,"An airplane",
    2,"Confession",
    2,"Gambling",
    2,"Gethsemane",
    2,"Gold plates",
    2,"Healing",
    2,"Keys",
    2,"Messiah",
    2,"Moses",
    2,"Perfection",
    2,"Procrastination",
    2,"Quoting a living apostle",
    2,"Specifying a target audience",
    2,"Sports",
    2,"Two people at organ",
    2,"Utah",
    2,"\"Ensign\" or \"Liahona\" magazine",
    3,"A definition",
    3,"A parable",
    3,"A question",
    3,"A statistic",
    3,"Courage",
    3,"Entertainment, movies, TV, or video games",
    3,"Family history or genealogy",
    3,"Glory",
    3,"Investigators",
    3,"Journals",
    3,"Power",
    3,"Sharing",
    3,"Video, photo, or quote appearing on screen",
    3,"\"Historic\"",
    3,"\"Supernal\"",
    4,"An Article of Faith",
    4,"Eternal",
    4,"Fellowship",
    4,"Friends",
    4,"God's omnipotence",
    4,"God's omniscience",
    4,"Grace",
    4,"Hate",
    4,"Mission story",
    4,"Modesty",
    4,"Money",
    4,"Nephi",
    4,"Offense",
    4,"Pain",
    4,"Pioneers",
    4,"Primary",
    4,"Salt Lake City",
    4,"Shepherd or sheep",
    4,"Spirits",
    4,"Strength",
    4,"Talents",
    4,"The Veil",
    4,"Witness",
    4,"Worthiness",
    4,"Zion",
    5,"A king",
    5,"A tree",
    5,"Asian nation or region",
    5,"Chastity",
    5,"Confirmation",
    5,"Daughters",
    5,"Education",
    5,"Eternity",
    5,"European nation or region",
    5,"Exercise",
    5,"Fathers",
    5,"Legacy",
    5,"Men",
    5,"Mothers",
    5,"Premortal life",
    5,"Relief Society",
    5,"Signs",
    5,"Sons",
    5,"Sorrow or depression",
    5,"Trials or burdens",
    5,"Women",
    5,"\"Beloved\"",
    6,"Adam, Eve, or Eden",
    6,"An animal",
    6,"Creation",
    6,"Fasting",
    6,"Joseph Smith",
    6,"Light",
    6,"Miracles",
    6,"Satan",
    6,"Setting an example",
    6,"Speaker wears blue tie",
    6,"Speaker wears red tie",
    6,"Time",
    7,"Any word starting with 'K'",
    7,"Any word starting with 'Q'",
    7,"Any word starting with 'U'",
    7,"Any word starting with 'V'",
    7,"Bodies",
    7,"Celestial Kingdom",
    7,"Fear",
    7,"Female speaker",
    7,"Food",
    7,"Laws",
    7,"Music or hymns",
    7,"Plan of salvation",
    7,"Second coming",
    7,"Story about children",
    7,"Virtue",
    7,"Wisdom",
    7,"\"Endure to the end\"",
    8,"Agency",
    8,"Bishops",
    8,"Evil",
    8,"Knowledge",
    8,"Mercy",
    8,"Ministering",
    8,"Restoration",
    8,"Sharing an Old Testament scripture",
    8,"Story about sickness or injury",
    8,"Temptation",
    8,"Truth",
    8,"Unity",
    8,"Worship",
    8,"\"The Church of Jesus Christ of Latter-day Saints\"",
    9,"Angels",
    9,"Sacrifice",
    9,"Sin",
    9,"Temples",
    9,"Testimonies",
    9,"Work",
];

