
var TITLE = "Download Bingo";
var BOARDTOP = "\"The Download\" Podcast Bingo";
var FREE = "\"Fair enough\"";
var USEFREE = 1;
var AUTOFREE = 0;

var allsayings = [
    32,"Laughing",
    16,"Spoiler",
    16,"Star Trek",
    16,"Star Wars",
    16,"\"Have you seen...\"",
    8,"A convention or cruise",
    8,"A non-Baker, non-Looney game",
    8,"A role-playing game",
    8,"A video streaming service",
    8,"A superhero",
    8,"An inside joke or obscure reference",
    8,"Cover art depicts Andy or Keith",
    8,"Fluxx",
    8,"Having trouble remembering",
    8,"Illness or injury",
    8,"Ranting",
    8,"Running low on time",
    8,"Time travel",
    8,"What may happen next in a series",
    4,"A favorite",
    4,"A disappointment",
    4,"A holiday",
    4,"A regret",
    4,"Comics",
    4,"Computers",
    4,"Cover art depicts an established fictional character",
    4,"Defending media (apologetics)",
    4,"Something from the fantasy genre",
    4,"Gloom",
    4,"Looney Pyramids",
    4,"Looney product besides Fluxx or pyramids",
    4,"Postponing a topic for a future conversation",
    2,"A Baker product besides Gloom",
    2,"A book",
    2,"A video game",
    2,"An animal",
    2,"Burning Man",
    2,"Dessert",
    2,"Doctor Who",
    2,"Fans",
    2,"Finances",
    2,"Fringe",
    2,"Getting technical",
    2,"Jenn or Kristin",
    2,"NASA or space",
    2,"Portland area",
    2,"Squeamishenss",
    2,"Suggesting a title for the episode",
    2,"The Twilight Zone",
    2,"Washington, D.C. area",
    2,"\"Anyway...\"",
    2,"\"On that note\"",
    2,"\"That's the thing...\"",
    1,"A project whose details can't be shared",
    1,"A robot",
    1,"Agreeing to disagree",
    1,"An alien",
    1,"An award",
    1,"Another podcast",
    1,"Battlestar Galactica",
    1,"Dreams",
    1,"Game-designing",
    1,"Gilligan's Island",
    1,"Kickstarter",
    1,"Magnet Interactive Studios",
    1,"Phillip K. Dick",
    1,"Playtesting",
    1,"Referring to an unrecorded conversation",
    1,"Story-writing",
    1,"The Bates Discordians",
    1,"The X-Files",
    1,"\"All I'm saying\"",
    1,"\"Anyhow...\"",
    1,"\"There you go\"",
];

