
var TITLE = "Download Bingo";
var BOARDTOP = "\"The Download\" Podcast Bingo";
var FREE = "Fair enough";
var USEFREE = 1;
var AUTOFREE = 0;

var allsayings = [
    81,"A streaming service",
    81,"Laughing",
    81,"Ranting",
    81,"Spoiler",
    81,"Star Trek",
    81,"Star Wars",
    81,"What should happen next in a series",
    81,"\"Have you seen...\"",
    27,"A convention or cruise",
    27,"A non-Baker, non-Looney game product",
    27,"A pun",
    27,"A role-playing game",
    27,"A superhero",
    27,"An inside joke or obscure reference",
    27,"Cover art depicts Andy or Keith",
    27,"Fluxx",
    27,"Having trouble remembering",
    27,"Illness or injury",
    27,"Looney Pyramids",
    27,"Running low on time",
    27,"Time travel",
    9,"A holiday",
    9,"Comics",
    9,"Computers",
    9,"Cover art depicts an established fictional character",
    9,"Gloom",
    9,"Looney product besides Fluxx or pyramids",
    9,"Postponing a topic for a future conversation",
    3,"A book",
    3,"A dessert",
    3,"An animal",
    3,"Burning Man",
    3,"Fans",
    3,"Fringe",
    3,"Futurama",
    3,"Jenn or Kristin",
    3,"NASA or space",
    3,"Portland area",
    3,"Washington, D.C. area",
    1,"\"All I'm saying\"",
    1,"A project whose details can't be shared",
    1,"A robot",
    1,"An alien",
    1,"An award",
    1,"Battlestar Galactica",
    1,"Doctor Who",
    1,"Dreams",
    1,"Game-designing",
    1,"Gilligan's Island",
    1,"Harry Potter",
    1,"Illimat",
    1,"Kickstarter",
    1,"Magnet Interactive Studios",
    1,"Parsely",
    1,"Playtesting",
    1,"Referring to an unrecorded conversation",
    1,"Story-writing",
    1,"The Lord of the Rings",
    1,"The Twilight Zone",
    1,"The X-Files",
];

