
var TITLE = "Download Bingo";
var BOARDTOP = "\"The Download\" Podcast Bingo";
var FREE = "Fair enough";
var USEFREE = 1;
var AUTOFREE = 0;

var allsayings = [
    81,"\"Have you seen...\"",
    81,"What should happen next in a series",
    81,"Star Wars",
    81,"Star Trek",
    81,"Spoiler",
    81,"Ranting",
    81,"Laughing",
    81,"A streaming service",
    81,"A pun",
    27,"Time travel",
    27,"Looney Pyramids",
    27,"Illness or injury",
    27,"Fluxx",
    27,"Cover art depicts Andy or Keith",
    27,"Andy and Keith running low on time",
    27,"A superhero",
    27,"A role-playing game",
    27,"A non-Baker, non-Looney game",
    27,"A convention",
    9,"Magic or mysterious force",
    9,"Looney product besides Fluxx or pyramids",
    9,"Gloom",
    9,"Cover art depicts an established fictional character",
    9,"Computers",
    9,"Comics",
    9,"A topic for a future conversation",
    9,"A holiday",
    3,"Washington, D.C. area",
    3,"Portland area",
    3,"NASA or space",
    3,"Futurama",
    3,"Fringe",
    3,"Burning Man",
    3,"A pet",
    3,"A dessert",
    3,"A book",
    1,"The X-Files",
    1,"The Twilight Zone",
    1,"Story-writing",
    1,"Referring to an unrecorded conversation",
    1,"Playtesting",
    1,"Parsely",
    1,"Magnet Interactive Studios",
    1,"Kristin",
    1,"Kickstarter",
    1,"Jenn",
    1,"Illimat",
    1,"Harry Potter",
    1,"Gilligan's Island",
    1,"Game-designing",
    1,"Doctor Who",
    1,"Battlestar Galactica",
    1,"An inside joke or obscure reference",
    1,"An ambient noise",
    1,"A project whose details can't be shared",
    1,"A cruise",
];

