var TITLE = "Murer Mystery Bingo";
var BOARDTOP = "BINGO for Murder Mysteries";
var FREE = "FREE";
var USEFREE = 1;
var AUTOFREE = 1;
var allsayings = [
    1,"Crying",
    2,"An animal",
    2,"Assumed or mistaken identity",
    2,"Solving an old or tangential case too",
    2,"Watching from window or hiding place",
    3,"A conspiracy",
    3,"A lawyer",
    3,"A party",
    3,"A trap",
    3,"Blood",
    3,"Nonviolent death",
    4,"Illness, injury, or disability",
    4,"A family secret",
    4,"Historical document (newspaper, photograph, journal, etc.)",
    4,"An unhappy family or divorce",
    4,"Haste, a chase, or unsafe driving",
    4,"Multiple deaths",
    4,"Overheard conversation",
    4,"Justice system edifice (police station, courtroom, prison, etc.)",
    4,"Sudden epiphany",
    4,"Body was moved or tampered with",
    5,"A note or letter",
    5,"Debt or money trouble",
    5,"A break-in",
    5,"Something buried",
    5,"Planted evidence",
    5,"Unpopular victim",
    6,"Expert analysis of evidence",
    6,"A search",
    6,"Suicide (suspected or attempted)",
    6,"Admitting happiness at death",
    6,"Illicit love",
    6,"Blackmail",
    6,"Theft",
    6,"Unsubstantiated alibi",
    6,"Inheritance or indemnity",
    6,"Time of death",
    7,"A threat or warning",
    7,"A doctor",
    7,"Violence",
    7,"Confronted for lying",
    8,"Indignation",
    8,"Sneaking around at night",
    9,"A gasp or scream",
    10,"An argument",
];


