var TITLE = "Murer Mystery Bingo";
var BOARDTOP = "BINGO for Murder Mysteries";
var FREE = "Free";
var USEFREE = 1;
var AUTOFREE = 0;
var allsayings = [
    1,"Admitting happiness at death",
    1,"Bad weather",
    1,"Crying",
    1,"Evidence tampering or planting",
    1,"Monologuing",
    1,"Poisoning or drugging",
    1,"Revenge",
    1,"Tracks",
    2,"A lock",
    2,"Acting on a hunch",
    2,"An animal",
    2,"Change of plans",
    2,"Confronted for lying",
    2,"Divorce or unhappy family",
    2,"International travel",
    2,"Mistaken identity or parentage",
    2,"Solving an old case",
    2,"Suicide (suspected or attempted)",
    2,"Establishing the time of the crime",
    2,"Watching from afar",
    4,"A search",
    4,"An arrest",
    4,"Blood",
    4,"Caught in the act",
    4,"Family secret",
    4,"Hurrying",
    4,"Illness, injury, or disability",
    4,"Newspaper or photograph",
    4,"Overheard conversation",
    4,"Police station",
    4,"Screaming",
    4,"Something buried",
    4,"Sudden epiphany",
    4,"Threat or warning",
    4,"Trap",
    8,"Argument",
    8,"Blackmail",
    8,"Conspiracy",
    8,"Doctor",
    8,"Expert analysis of evidence or body",
    8,"Financial straits",
    8,"Forbidden love",
    8,"Inheritance or insurance",
    8,"Lawyer",
    8,"Note or letter",
    8,"Party",
    8,"Sneaking around at night",
    8,"Theft",
    8,"Trespassing",
    8,"Unsubstantiated alibi",
    8,"Violence",
];


