var TITLE = "Murer Mystery Bingo";
var BOARDTOP = "BINGO for Murder Mysteries";
var FREE = "Murder!";
var USEFREE = 1;
var AUTOFREE = 0;
var allsayings = [
    1,"Admitting happiness at death",
    1,"An animal",
    1,"Bad weather",
    1,"Crying",
    1,"Nonviolent death",
    1,"Secret passage",
    1,"Solving an old case",
    1,"Summation gathering",
    1,"Tracks",
    1,"Watching from window or hiding place",
    2,"A change of plans",
    2,"Confronted for lying",
    2,"Divorce or unhappy family",
    2,"Illicit love",
    2,"Mistaken identity",
    2,"Time of the crime",
    4,"A family secret",
    4,"A search",
    4,"A threat or warning",
    4,"A trap",
    4,"Blood",
    4,"Body was tampered with",
    4,"Catching someone in the act",
    4,"Financial straits",
    4,"Historical record (newspaper, photograph, painting, etc.)",
    4,"Hurrying",
    4,"Illness, injury, or disability",
    4,"Overheard conversation",
    4,"Something buried",
    4,"Sudden epiphany",
    4,"Suicide (suspected or attempted)",
    4,"Unpopular victim",
    8,"A break-in",
    8,"A conspiracy",
    8,"A doctor",
    8,"A gasp or scream",
    8,"A lawyer",
    8,"A note or letter",
    8,"A party",
    8,"An argument",
    8,"Blackmail",
    8,"Destroying evidence",
    8,"Expert analysis of evidence",
    8,"Indignation",
    8,"Inheritance or insurance",
    8,"Justice system building",
    8,"Planted evidence",
    8,"Sneaking around at night",
    8,"Theft",
    8,"Violence",
    8,"Weak alibi",
];


